[build-system]
# Minimum requirements for the build system to execute.
requires = [
    "setuptools",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target_version = ['py310', 'py311']
preview = true
# Exclude irrelevant directories for formatting
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.vscode
  | \.pytest_cache
  | \.idea
  | build
  | dist
)/
'''

[tool.ruff]
# max line length for black
line-length = 88
target-version = "py310"
ignore = [
    # check ignored by default in flake8. Meaning unclear.
    "E24",
    # continuation line under-indented
    "E121",
    # closing bracket does not match indentation
    "E123",
    # continuation line over-indented for hanging indent
    "E126",
    # space before : (needed for how black formats slicing)
    "E203",
    # missing whitespace around arithmetic operator
    "E226",
    # multiple statements on one line (def)
    "E704",
    # do not assign a lambda expression, use a def
    "E731",
    # do not use variables named 'l', 'O', or 'I'
    "E741",
    # line break before binary operator
    "W503",
    # line break after binary operator
    "W504"
]
extend-exclude = [
    ".git",
    "__pycache__",
]

[tool.ruff.per-file-ignores]
# It's fine not to put the import at the top of the file in the examples
# folder.
"examples/*" = ["E402"]
"doc/conf.py" = ["E402"]

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
filterwarnings = [
    # Turn deprecation warnings into errors
    "error::FutureWarning",
    "error::DeprecationWarning",
    "error::numpy.VisibleDeprecationWarning",

    # Ignore warning from np.in1d since the future behavior is already the desired
    # behavior. TODO remove when numpy min version >= 1.25.
    'ignore:elementwise\ comparison\ failed:FutureWarning',
]
